name: Github CI build

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]


env:
  RELEASE: 3.1.0.12

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: mkdir output

    - name: Build armv7hl
      id: build_armv7hl
      uses: coderus/github-sfos-build@master
      with:
        release: ${{ env.RELEASE }}
        arch: armv7hl

#    - name: Build aarch64
#      id: build_aarch64
#      uses: coderus/github-sfos-build@master
#      with:
#        release: ${{ env.RELEASE }}
#        arch: aarch64

    - name: Build i486
      id: build_i486
      uses: coderus/github-sfos-build@master
      with:
        release: ${{ env.RELEASE }}
        arch: i486
 
    - name: Upload build result
      uses: actions/upload-artifact@v3
      with:
        path: RPMS/*
